api:
  openai:
    model: gpt-4-turbo
    temperature: 0.7
    max_tokens: 4000
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
  deepseek:
    model: deepseek-chat
    temperature: 0.7
    max_tokens: 4000

agent_roles:
  research:
    title: Research Director
    skills: [research, data_analysis, validation]
    response_style: thorough and evidence-based
  analysis:
    title: Analysis Director
    skills: [data_analysis, pattern_recognition]
    response_style: analytical and data-driven
  validation:
    title: Quality Assurance Director
    skills: [quality_control, validation]
    response_style: detail-oriented and thorough
  creative:
    title: Creative Director
    skills: [content_creation, innovation]
    response_style: innovative and imaginative
  tech:
    title: Technology Director
    skills: [technical_implementation, system_integration]
    response_style: technical and practical

performance:
  timeouts:
    research: 300
    analysis: 180
    content_generation: 240
    validation: 120
  retry:
    max_attempts: 3
    delay_base: 2
    max_delay: 30

monitoring:
  enabled: true
  metrics_interval: 60
  log_level: INFO

security:
  max_requests: 100
  rate_limit: 60/minute
  allowed_ips: [10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16]